# frozen_string_literal: true

require "fileutils"

module Unmagic
  class Icon
    class Scanner
      ICONS_FILE = "app/assets/builds/unmagic/icons.txt"

      class << self
        def scan
          icons = []
          libraries = Library.discover_all

          if libraries.empty?
            puts "No libraries found, nothing to scan"
            exit
          end

          # Build regex patterns for each library
          libraries.each_key do |library_name|
            pattern = %r{#{Regexp.escape(library_name)}/[a-z0-9_-]+}i
            path = Rails.root.join("{app,lib,spec,test}/**/*.{rb,erb,html,haml}")
            puts "Scanning #{path} for #{pattern}"

            # Search Ruby and template files
            Dir.glob(path).each do |file|
              content = File.read(file)
              icons.concat(content.scan(pattern))
            end
          end

          icons.uniq.sort
        end

        def write!
          icons = scan
          file_path = Rails.root.join(ICONS_FILE)

          FileUtils.mkdir_p(File.dirname(file_path))

          File.write(file_path, <<~TXT)
            # Generated by unmagic:icons:build at #{Time.current}
            # Found #{icons.count} icon references

            #{icons.join("\n")}
          TXT

          puts "Wrote #{icons.count} icon references to #{ICONS_FILE}"
          icons
        end
      end
    end
  end
end
